# ===== LOADSCREENS CONFIGURATION =====
# Advanced animated loading screen system with PacketEvents
# Version: 3.0 Ultimate Edition

# === GLOBAL SETTINGS ===
global:
  enabled: true
  debug: true
  use_packetevents: true          # Use PacketEvents for better UI control
  placeholder_support: true       # Enable PlaceholderAPI support
  async_processing: true
  max_concurrent_sessions: 50     # Prevent server overload

# === CUSTOM LOADSCREEN TYPES ===
loadscreen_types:
  # Default join loadscreen
  join:
    enabled: true
    timer_delay: 5               # Seconds to wait after join before starting loadscreen
    duration: 100
    frame_interval: 4
    fade_in_duration: 20           # Ticks for fade in effect (1 second = 20 ticks)
    fade_out_duration: 20          # Ticks for fade out effect
    fade_in_opacity_start: 0       # Starting opacity for fade in (0-255)
    fade_out_opacity_end: 0        # Ending opacity for fade out (0-255)
    fade_smooth: true              # Enable smooth fading
    font: "minecraft:default"
    frames:
      - "ꐑ"  # load_1
      - "ꐒ"  # load_2
      - "ꐓ"  # load_3
      - "ꐔ"  # load_4
      - "ꐕ"  # load_5
      - "ꐖ"  # load_6
      - "ꐗ"  # load_7

    # Positioning & Effects
    scale: 1.5
    y_offset: 0.0
    z_offset: 3.5
    x_offset: 0.0
    opacity: 255                   # Maximum opacity during animation
    brightness: 15
    look_yaw: 0.0                  # Yaw to force player to look at (0 = south, 90 = west, 180 = north, -90/270 = east)
    look_pitch: 0.0                # Pitch to force player to look at (0 = horizontal, 90 = straight down, -90 = straight up)


    # Visual Effects
    pulse_effect: false
    rainbow_text: false
    typewriter_effect: true
    typewriter_speed: 3

    # Sound
    play_sound: true
    sound_name: "minecraft:entity.player.levelup"
    sound_volume: 0.3
    sound_pitch: 1.2

    # Conditions
    require_permission: false
    first_join_only: false
    cooldown_seconds: 10

    # Triggers
    show_on_join: true

  # Player leave/quit loadscreen
  leave:
    enabled: true
    timer_delay: 0                # Immediate
    duration: 40                  # Shorter duration
    frame_interval: 2
    fade_in_duration: 10
    fade_out_duration: 10
    fade_in_opacity_start: 0
    fade_out_opacity_end: 0
    fade_smooth: true
    font: "minecraft:default"
    frames:
      - "ꐙ"  # leave_1
      - "ꐠ"  # leave_2
      - "ꐡ"  # leave_3
      - "ꐢ"  # leave_4
      - "ꐣ"  # leave_5
      - "ꐤ"  # leave_6


    scale: 3
    y_offset: 0.0
    z_offset: 3.5
    x_offset: 0.0
    opacity: 255                   # Maximum opacity during animation
    brightness: 15
    look_yaw: 0.8                  # Yaw to force player to look at (0 = south, 90 = west, 180 = north, -90/270 = east)
    look_pitch: -4.5                # Pitch to force player to look at (0 = horizontal, 90 = straight down, -90 = straight up)


    rainbow_text: false
    rainbow_speed: 0.1

    play_sound: true
    sound_name: "minecraft:block.note_block.chime"
    sound_volume: 0.5
    sound_pitch: 0.8

    # Special: Show to other players when someone leaves
    show_to_others: true
    show_range: 50.0              # Blocks range

    # Leave Command Feature
    allow_leave_command: true     # Enable /leave and /exit commands (if false, commands are disabled entirely)

  # World change/teleport loadscreen
  world_change:
    enabled: true
    timer_delay: 1                # Small delay
    duration: 60
    frame_interval: 3
    fade_in_duration: 15
    fade_out_duration: 15
    fade_in_opacity_start: 0
    fade_out_opacity_end: 0
    fade_smooth: true
    font: "minecraft:default"
    frames:
      - "ꐥ"  # leave_1
      - "ꐦ"  # leave_2
      - "ꐧ"  # leave_3
      - "ꐨ"  # leave_4
      - "ꐩ"  # leave_5
      - "ꐪ"  # leave_6

    scale: 3
    y_offset: 0.0
    z_offset: 3.5
    x_offset: 0.0
    opacity: 255                   # Maximum opacity during animation
    brightness: 15
    look_yaw: 0.8                  # Yaw to force player to look at (0 = south, 90 = west, 180 = north, -90/270 = east)
    look_pitch: -4.5                # Pitch to force player to look at (0 = horizontal, 90 = straight down, -90 = straight up)


    wobble_effect: false
    wobble_intensity: 0.05
    wobble_speed: 0.3

    play_sound: true
    sound_name: "minecraft:block.portal.ambient"
    sound_volume: 0.4
    sound_pitch: 1.0

    show_on_world_change: true
    show_on_teleport: true
    min_teleport_distance: 1    # Minimum distance to trigger
  # Respawn loadscreen
  respawn:
    enabled: true
    timer_delay: 10               # Wait a bit after respawn
    duration: 80
    frame_interval: 4
    fade_in_duration: 20
    fade_out_duration: 20
    fade_in_opacity_start: 0
    fade_out_opacity_end: 0
    fade_smooth: true
    font: "minecraft:default"
    frames:
      - "§cRespawning..."
      - "§6Getting back up..."
      - "§aReady for action!"

    scale: 1.3
    y_offset: 0.2
    z_offset: 2.0
    opacity: 255
    brightness: 15


    pulse_effect: true
    pulse_intensity: 0.3
    pulse_speed: 0.2

    play_sound: true
    sound_name: "minecraft:entity.player.hurt"
    sound_volume: 0.2
    sound_pitch: 0.5

    show_on_respawn: true

  # Custom event loadscreen (for API usage)
  custom:
    enabled: true
    timer_delay: 0
    duration: 120
    frame_interval: 5
    fade_in_duration: 30
    fade_out_duration: 30
    fade_in_opacity_start: 0
    fade_out_opacity_end: 0
    fade_smooth: true
    font: "minecraft:default"
    frames:
      - "%custom_message_1%"
      - "%custom_message_2%"
      - "%custom_message_3%"

    scale: 2.0
    y_offset: 0.0
    z_offset: 3.0
    opacity: 255
    brightness: 15


    rainbow_text: true
    typewriter_effect: true
    typewriter_speed: 2

    play_sound: true
    sound_name: "minecraft:block.note_block.pling"
    sound_volume: 0.5
    sound_pitch: 1.0

# === PACKET EVENTS SETTINGS ===
packet_settings:
  # NUCLEAR MOVEMENT BLOCKING
  block_movement_packets: true        # Block ALL movement packets
  prevent_head_movement: true         # STRICT head movement prevention
  lock_position: true                 # Lock position with teleportation
  rotation_lock_threshold: 0.01       # How precise rotation lock should be

  # COMPLETE UI BLOCKING
  hide_hotbar: true
  hide_experience: true
  hide_health: true
  hide_food: true
  hide_armor: true
  hide_air: true
  hide_mount_health: true
  hide_crosshair: true
  hide_actionbar: true
  hide_boss_bar: true
  hide_scoreboard: true
  hide_tab_list: true
  hide_chat: true

  # NUCLEAR OPTIONS
  block_all_input: true              # Block ALL player input
  make_invisible: true               # Make player completely invisible
  use_spectator_mode: true           # Use spectator mode for UI hiding
  strict_packet_blocking: true       # Block ALL packets except admin commands

  # BLINDNESS EFFECT
  apply_blindness_effect: true     # Apply blindness effect to player

# === PLACEHOLDER SETTINGS ===
placeholders:
  update_interval: 5              # Ticks between placeholder updates
  cache_duration: 100             # Ticks to cache placeholder values

  # Custom placeholders for loadscreens
  custom_placeholders:
    "%custom_message_1%": "§6This is a custom message!"
    "%custom_message_2%": "§bYou can customize this!"
    "%custom_message_3%": "§aEnjoy the loadscreen!"

# === PERFORMANCE SETTINGS ===
performance:
  max_view_distance: 2.0
  cleanup_on_disconnect: true
  async_placeholder_parsing: true
  cache_parsed_frames: true
  max_cache_size: 1000

# === COMPATIBILITY ===
compatibility:
  check_plugins:
    - "PlaceholderAPI"
    - "PacketEvents"
  fallback_mode: true             # Fallback if dependencies missing
  legacy_support: false           # Support older MC versions